// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zllmltrjfjooxzgopplz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpsbG1sdHJqZmpvb3h6Z29wcGx6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyMjA3NDksImV4cCI6MjA2Nzc5Njc0OX0.IxmiN84MVF_HfNTa1LNiU1tAiYAa6cnIWUyuKdFvE7E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});